name: Sauce Demo UI Cypress Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  sauce-demo-ui-cypress:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm ci
        
      - name: Run Sauce Demo UI Cypress Tests
        run: CYPRESS_username=${{ secrets.USERNAME }} CYPRESS_password=${{ secrets.PASSWORD }}  npm run cypress:run:all

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress Screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: cypress/reports

      - name: Prepare Cypress report for GitHub Pages
        run: |
          mkdir -p public/cypress
          cp -r cypress/reports/* public/cypress/
            
      - name: Create custom index.html
        run: |
          echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Test Reports</title></head><body><h1>Test Reports</h1><ul>' > public/index.html
          echo '<li><a href="./cypress/chrome/chrome-ats-report.html">Chrome Report</a></li>' >> public/index.html
          echo '<li><a href="./cypress/edge/edge-ats-report.html">Edge Report</a></li>' >> public/index.html
          echo '<li><a href="./cypress/electron/electron-ats-report.html">Electron Report</a></li>' >> public/index.html
          echo '<li><a href="./cypress/firefox/firefox-ats-report.html">Firefox Report</a></li>' >> public/index.html
          echo '</ul></body></html>' >> public/index.html
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
